
//SyncTestScenario.xsd and resulting generated code
//Cloud

//Created by DavidBruck.

//Copyright (c) Cloud.com. All rights reserved.

//Manually copy this copyright declaration to the header of any generated code files created from this schema

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace SyncTestServer.Model
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd", IsNullable = false)]
    public partial class Scenario
    {

        private Copyright copyrigntField;

        private ClientType[] clientsField;

        private ScenarioServer serverField;

        private OperationType[] initialOperationsField;

        private ScenarioParallelOperationSet[] regularOperationsField;

        /// <remarks/>
        public Copyright Copyrignt
        {
            get
            {
                return this.copyrigntField;
            }
            set
            {
                this.copyrigntField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Client", IsNullable = false)]
        public ClientType[] Clients
        {
            get
            {
                return this.clientsField;
            }
            set
            {
                this.clientsField = value;
            }
        }

        /// <remarks/>
        public ScenarioServer Server
        {
            get
            {
                return this.serverField;
            }
            set
            {
                this.serverField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Operation", IsNullable = false)]
        public OperationType[] InitialOperations
        {
            get
            {
                return this.initialOperationsField;
            }
            set
            {
                this.initialOperationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("ParallelOperationSet", IsNullable = false)]
        public ScenarioParallelOperationSet[] RegularOperations
        {
            get
            {
                return this.regularOperationsField;
            }
            set
            {
                this.regularOperationsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class Copyright
    {

        private string fileNameField;

        private CopyrightCopyright copyright1Field;

        private string creatorField;

        /// <remarks/>
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Copyright")]
        public CopyrightCopyright Copyright1
        {
            get
            {
                return this.copyright1Field;
            }
            set
            {
                this.copyright1Field = value;
            }
        }

        /// <remarks/>
        public string Creator
        {
            get
            {
                return this.creatorField;
            }
            set
            {
                this.creatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public enum CopyrightCopyright
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Implementation of SyncTestScenario.xsd XML Schema. Cloud. Copyright (c) Cloud.com" +
            ". All rights reserved.")]
        ImplementationofSyncTestScenarioxsdXMLSchemaCloudCopyrightcCloudcomAllrightsreserved,
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ModifiedChangeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RenamedChangeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeletedChangeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreatedChangeType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class FileChangeType
    {

        private FileChangeTypeType typeField;

        /// <remarks/>
        public FileChangeTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public enum FileChangeTypeType
    {

        /// <remarks/>
        Created,

        /// <remarks/>
        Deleted,

        /// <remarks/>
        Renamed,

        /// <remarks/>
        Modified,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ModifiedChangeType : FileChangeType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class RenamedChangeType : FileChangeType
    {

        private string oldRelativePathFromRootField;

        /// <remarks/>
        public string OldRelativePathFromRoot
        {
            get
            {
                return this.oldRelativePathFromRootField;
            }
            set
            {
                this.oldRelativePathFromRootField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class DeletedChangeType : FileChangeType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class CreatedChangeType : FileChangeType
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SleepOperationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WaitAllOperationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileOrFolderOperationType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class OperationType
    {

        private OperationTypeType typeField;

        /// <remarks/>
        public OperationTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public enum OperationTypeType
    {

        /// <remarks/>
        FileOrFolderChange,

        /// <remarks/>
        WaitForPending,

        /// <remarks/>
        Sleep,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class SleepOperationType : OperationType
    {

        private int millisecondTimeSpanField;

        /// <remarks/>
        public int MillisecondTimeSpan
        {
            get
            {
                return this.millisecondTimeSpanField;
            }
            set
            {
                this.millisecondTimeSpanField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class WaitAllOperationType : OperationType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class FileOrFolderOperationType : OperationType
    {

        private bool changeStartsOnServerField;

        private FileChangeType fileChangeTypeField;

        private FileOrFolderType fileOrFolderField;

        /// <remarks/>
        public bool ChangeStartsOnServer
        {
            get
            {
                return this.changeStartsOnServerField;
            }
            set
            {
                this.changeStartsOnServerField = value;
            }
        }

        /// <remarks/>
        public FileChangeType FileChangeType
        {
            get
            {
                return this.fileChangeTypeField;
            }
            set
            {
                this.fileChangeTypeField = value;
            }
        }

        /// <remarks/>
        public FileOrFolderType FileOrFolder
        {
            get
            {
                return this.fileOrFolderField;
            }
            set
            {
                this.fileOrFolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FolderType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FileType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class FileOrFolderType
    {

        private bool isFolderField;

        private string relativePathFromRootField;

        private System.DateTime uTCCreatedDateTimeField;

        /// <remarks/>
        public bool IsFolder
        {
            get
            {
                return this.isFolderField;
            }
            set
            {
                this.isFolderField = value;
            }
        }

        /// <remarks/>
        public string RelativePathFromRoot
        {
            get
            {
                return this.relativePathFromRootField;
            }
            set
            {
                this.relativePathFromRootField = value;
            }
        }

        /// <remarks/>
        public System.DateTime UTCCreatedDateTime
        {
            get
            {
                return this.uTCCreatedDateTimeField;
            }
            set
            {
                this.uTCCreatedDateTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class FolderType : FileOrFolderType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class FileType : FileOrFolderType
    {

        private string mD5Field;

        private System.DateTime uTCModifiedDateTimeField;

        private long sizeField;

        private string storageKeyField;

        /// <remarks/>
        public string MD5
        {
            get
            {
                return this.mD5Field;
            }
            set
            {
                this.mD5Field = value;
            }
        }

        /// <remarks/>
        public System.DateTime UTCModifiedDateTime
        {
            get
            {
                return this.uTCModifiedDateTimeField;
            }
            set
            {
                this.uTCModifiedDateTimeField = value;
            }
        }

        /// <remarks/>
        public long Size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        public string StorageKey
        {
            get
            {
                return this.storageKeyField;
            }
            set
            {
                this.storageKeyField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServerUserFolder))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServerUserFile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ServerUserItem
    {

        private string uuidField;

        private bool isFolderField;

        /// <remarks/>
        public string Uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }

        /// <remarks/>
        public bool IsFolder
        {
            get
            {
                return this.isFolderField;
            }
            set
            {
                this.isFolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ServerUserFolder : ServerUserItem
    {

        private FolderType folderField;

        /// <remarks/>
        public FolderType Folder
        {
            get
            {
                return this.folderField;
            }
            set
            {
                this.folderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ServerUserFile : ServerUserItem
    {

        private string mD5Field;

        private FileType fileField;

        /// <remarks/>
        public string MD5
        {
            get
            {
                return this.mD5Field;
            }
            set
            {
                this.mD5Field = value;
            }
        }

        /// <remarks/>
        public FileType File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServerPhysicalStorageType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ServerStorageType
    {

        private StorageType typeField;

        /// <remarks/>
        public StorageType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public enum StorageType
    {

        /// <remarks/>
        PhysicalLocation,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ServerPhysicalStorageType : ServerStorageType
    {

        private string rootPathField;

        /// <remarks/>
        public string RootPath
        {
            get
            {
                return this.rootPathField;
            }
            set
            {
                this.rootPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ServerDeviceType
    {

        private string uDidField;

        private string aKeyField;

        private string friendlyNameField;

        /// <remarks/>
        public string UDid
        {
            get
            {
                return this.uDidField;
            }
            set
            {
                this.uDidField = value;
            }
        }

        /// <remarks/>
        public string AKey
        {
            get
            {
                return this.aKeyField;
            }
            set
            {
                this.aKeyField = value;
            }
        }

        /// <remarks/>
        public string FriendlyName
        {
            get
            {
                return this.friendlyNameField;
            }
            set
            {
                this.friendlyNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ServerUserType
    {

        private string uUidField;

        private string usernameField;

        private string passwordField;

        private ServerDeviceType[] devicesField;

        private CloudFolderType cloudFolderField;

        /// <remarks/>
        public string UUid
        {
            get
            {
                return this.uUidField;
            }
            set
            {
                this.uUidField = value;
            }
        }

        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Device", IsNullable = false)]
        public ServerDeviceType[] Devices
        {
            get
            {
                return this.devicesField;
            }
            set
            {
                this.devicesField = value;
            }
        }

        /// <remarks/>
        public CloudFolderType CloudFolder
        {
            get
            {
                return this.cloudFolderField;
            }
            set
            {
                this.cloudFolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhysicalLocationCloudFolderType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class CloudFolderType
    {

        private StorageType typeField;

        private InitialCloudFolderDataType initialDataField;

        private string rootPathField;

        /// <remarks/>
        public StorageType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        public InitialCloudFolderDataType InitialData
        {
            get
            {
                return this.initialDataField;
            }
            set
            {
                this.initialDataField = value;
            }
        }

        /// <remarks/>
        public string RootPath
        {
            get
            {
                return this.rootPathField;
            }
            set
            {
                this.rootPathField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DefinedValuesForCloudFolderType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BuildInitialDataFromCloudFolderType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class InitialCloudFolderDataType
    {

        private InitialCloudFolderDataTypeType typeField;

        /// <remarks/>
        public InitialCloudFolderDataTypeType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public enum InitialCloudFolderDataTypeType
    {

        /// <remarks/>
        BuildFromCloudFolder,

        /// <remarks/>
        DefinedValues,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class DefinedValuesForCloudFolderType : InitialCloudFolderDataType
    {

        private FileOrFolderType[] pathsWithMetadataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("PathWithMetadata", IsNullable = false)]
        public FileOrFolderType[] PathsWithMetadata
        {
            get
            {
                return this.pathsWithMetadataField;
            }
            set
            {
                this.pathsWithMetadataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class BuildInitialDataFromCloudFolderType : InitialCloudFolderDataType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class PhysicalLocationCloudFolderType : CloudFolderType
    {
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NonAuthenticatedClientType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AuthenticatedClientType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ClientLoginType
    {

        private bool alreadyAuthenticatedField;

        private string friendlyNameField;

        private string usernameField;

        private string passwordField;

        /// <remarks/>
        public bool AlreadyAuthenticated
        {
            get
            {
                return this.alreadyAuthenticatedField;
            }
            set
            {
                this.alreadyAuthenticatedField = value;
            }
        }

        /// <remarks/>
        public string FriendlyName
        {
            get
            {
                return this.friendlyNameField;
            }
            set
            {
                this.friendlyNameField = value;
            }
        }

        /// <remarks/>
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class NonAuthenticatedClientType : ClientLoginType
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class AuthenticatedClientType : ClientLoginType
    {

        private string initialAKeyField;

        private string initialUDidField;

        private string initialUUidField;

        /// <remarks/>
        public string InitialAKey
        {
            get
            {
                return this.initialAKeyField;
            }
            set
            {
                this.initialAKeyField = value;
            }
        }

        /// <remarks/>
        public string InitialUDid
        {
            get
            {
                return this.initialUDidField;
            }
            set
            {
                this.initialUDidField = value;
            }
        }

        /// <remarks/>
        public string InitialUUid
        {
            get
            {
                return this.initialUUidField;
            }
            set
            {
                this.initialUUidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ClientType
    {

        private ClientLoginType loginField;

        private CloudFolderType cloudFolderField;

        /// <remarks/>
        public ClientLoginType Login
        {
            get
            {
                return this.loginField;
            }
            set
            {
                this.loginField = value;
            }
        }

        /// <remarks/>
        public CloudFolderType CloudFolder
        {
            get
            {
                return this.cloudFolderField;
            }
            set
            {
                this.cloudFolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ScenarioServer
    {

        private ServerUserType[] usersField;

        private ServerStorageType storageField;

        private ServerUserItem[] userItemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("User", IsNullable = false)]
        public ServerUserType[] Users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }

        /// <remarks/>
        public ServerStorageType Storage
        {
            get
            {
                return this.storageField;
            }
            set
            {
                this.storageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("UserItem", IsNullable = false)]
        public ServerUserItem[] UserItems
        {
            get
            {
                return this.userItemsField;
            }
            set
            {
                this.userItemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Cloud.com/SyncTestScenario.xsd")]
    public partial class ScenarioParallelOperationSet
    {

        private OperationType[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Operation")]
        public OperationType[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
}
