//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace win_client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("win_client.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string appDelegateErrorInstallingButtonIgnore {
            get {
                return ResourceManager.GetString("appDelegateErrorInstallingButtonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string appDelegateErrorInstallingButtonTryAgain {
            get {
                return ResourceManager.GetString("appDelegateErrorInstallingButtonTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh Snap!  Something happened..
        /// </summary>
        public static string appDelegateErrorInstallingHeader {
            get {
                return ResourceManager.GetString("appDelegateErrorInstallingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string appDelegateErrorInstallingTitle {
            get {
                return ResourceManager.GetString("appDelegateErrorInstallingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while creating the Cloud folder..
        /// </summary>
        public static string appDelegateExceptionCreatingFolder {
            get {
                return ResourceManager.GetString("appDelegateExceptionCreatingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating your account..
        /// </summary>
        public static string createNewAccountErrorHeader {
            get {
                return ResourceManager.GetString("createNewAccountErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Network Bandwidth Preferences.
        /// </summary>
        public static string DialogPreferencesNetworkBandwidthTitle {
            get {
                return ResourceManager.GetString("DialogPreferencesNetworkBandwidthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Network Proxy Server Preferences.
        /// </summary>
        public static string DialogPreferencesNetworkProxiesTitle {
            get {
                return ResourceManager.GetString("DialogPreferencesNetworkProxiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already a folder called Cloud in {0}.  Do you want to merge all the existing files in that folder to your Cloud folder, or select a new Cloud folder location?.
        /// </summary>
        public static string folderExitTextFieldBody {
            get {
                return ResourceManager.GetString("folderExitTextFieldBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string folderExitTextFieldButtonMerge {
            get {
                return ResourceManager.GetString("folderExitTextFieldButtonMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new location.
        /// </summary>
        public static string folderExitTextFieldButtonSelectNewLocation {
            get {
                return ResourceManager.GetString("folderExitTextFieldButtonSelectNewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge with existing Cloud Folder?.
        /// </summary>
        public static string folderExitTextFieldHeader {
            get {
                return ResourceManager.GetString("folderExitTextFieldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Exists!.
        /// </summary>
        public static string folderExitTextFieldTitle {
            get {
                return ResourceManager.GetString("folderExitTextFieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string folderSelectionSimpleButtonLeftText {
            get {
                return ResourceManager.GetString("folderSelectionSimpleButtonLeftText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string folderSelectionSimpleButtonRightText {
            get {
                return ResourceManager.GetString("folderSelectionSimpleButtonRightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string generalCancelButtonContent {
            get {
                return ResourceManager.GetString("generalCancelButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh Snap!  Something happened..
        /// </summary>
        public static string generalErrorTitle {
            get {
                return ResourceManager.GetString("generalErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string generalOkButtonContent {
            get {
                return ResourceManager.GetString("generalOkButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error logging in..
        /// </summary>
        public static string loginErrorHeader {
            get {
                return ResourceManager.GetString("loginErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue syncing, please restore your Cloud folder.  You may also choose to remove this computer from your account and exit the application..
        /// </summary>
        public static string pageCloudFolderMissingBodyMesssage {
            get {
                return ResourceManager.GetString("pageCloudFolderMissingBodyMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred while removing your computer from your acccount on the server..
        /// </summary>
        public static string pageCloudFolderMissingErrorBody {
            get {
                return ResourceManager.GetString("pageCloudFolderMissingErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh Snap!  Something happened..
        /// </summary>
        public static string pageCloudFolderMissingErrorHeader {
            get {
                return ResourceManager.GetString("pageCloudFolderMissingErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string pageCloudFolderMissingErrorRightButtonContent {
            get {
                return ResourceManager.GetString("pageCloudFolderMissingErrorRightButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.com.
        /// </summary>
        public static string pageCloudFolderMissingErrorTitle {
            get {
                return ResourceManager.GetString("pageCloudFolderMissingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the location for your Cloud folder.  A folder named Cloud will be created inside the folder you select..
        /// </summary>
        public static string pageCloudFolderMissingFolderBrowserDescription {
            get {
                return ResourceManager.GetString("pageCloudFolderMissingFolderBrowserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate....
        /// </summary>
        public static string pageCloudFolderMissingOkButtonLocate {
            get {
                return ResourceManager.GetString("pageCloudFolderMissingOkButtonLocate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string pageCloudFolderMissingOkButtonRestore {
            get {
                return ResourceManager.GetString("pageCloudFolderMissingOkButtonRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud About Preferences.
        /// </summary>
        public static string PagePreferencesAboutTitle {
            get {
                return ResourceManager.GetString("PagePreferencesAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Account Preferences.
        /// </summary>
        public static string PagePreferencesAccountTitle {
            get {
                return ResourceManager.GetString("PagePreferencesAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Advanced Preferences.
        /// </summary>
        public static string PagePreferencesAdvancedTitle {
            get {
                return ResourceManager.GetString("PagePreferencesAdvancedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud General Preferences.
        /// </summary>
        public static string PagePreferencesGeneralTitle {
            get {
                return ResourceManager.GetString("PagePreferencesGeneralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Network Preferences.
        /// </summary>
        public static string PagePreferencesNetworkTitle {
            get {
                return ResourceManager.GetString("PagePreferencesNetworkTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/PageCloudAlreadyRunning.xaml.
        /// </summary>
        public static string startupUriAlreadyRunning {
            get {
                return ResourceManager.GetString("startupUriAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/PageCloudFolderMissing.xaml.
        /// </summary>
        public static string startupUriCloudFolderMissing {
            get {
                return ResourceManager.GetString("startupUriCloudFolderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/PageHome.xaml.
        /// </summary>
        public static string startupUriFirstTimeSetup {
            get {
                return ResourceManager.GetString("startupUriFirstTimeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Views/PageInvisible.xaml.
        /// </summary>
        public static string startupUriPageInvisible {
            get {
                return ResourceManager.GetString("startupUriPageInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        public static string SystemTrayContextMenuCheckForUpdates {
            get {
                return ResourceManager.GetString("SystemTrayContextMenuCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string SystemTrayContextMenuExit {
            get {
                return ResourceManager.GetString("SystemTrayContextMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        public static string SystemTrayContextMenuHeader {
            get {
                return ResourceManager.GetString("SystemTrayContextMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences....
        /// </summary>
        public static string SystemTrayContextMenuPreferences {
            get {
                return ResourceManager.GetString("SystemTrayContextMenuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon SystemTrayIcon {
            get {
                object obj = ResourceManager.GetObject("SystemTrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings {0}!  Welcome to Cloud!.
        /// </summary>
        public static string tourPage1Greeting {
            get {
                return ResourceManager.GetString("tourPage1Greeting", resourceCulture);
            }
        }
    }
}
