//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace win_client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("win_client.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string appDelegateErrorInstallingButtonIgnore {
            get {
                return ResourceManager.GetString("appDelegateErrorInstallingButtonIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try Again.
        /// </summary>
        public static string appDelegateErrorInstallingButtonTryAgain {
            get {
                return ResourceManager.GetString("appDelegateErrorInstallingButtonTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh Snap!  Something happened..
        /// </summary>
        public static string appDelegateErrorInstallingHeader {
            get {
                return ResourceManager.GetString("appDelegateErrorInstallingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string appDelegateErrorInstallingTitle {
            get {
                return ResourceManager.GetString("appDelegateErrorInstallingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while creating the Cloud folder..
        /// </summary>
        public static string appDelegateExceptionCreatingFolder {
            get {
                return ResourceManager.GetString("appDelegateExceptionCreatingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s already a folder called Cloud in {0}.  Do you want to merge all the existing files in that folder to your Cloud folder, or select a new Cloud folder location?.
        /// </summary>
        public static string folderExitTextFieldBody {
            get {
                return ResourceManager.GetString("folderExitTextFieldBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge.
        /// </summary>
        public static string folderExitTextFieldButtonMerge {
            get {
                return ResourceManager.GetString("folderExitTextFieldButtonMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a new location.
        /// </summary>
        public static string folderExitTextFieldButtonSelectNewLocation {
            get {
                return ResourceManager.GetString("folderExitTextFieldButtonSelectNewLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge with existing Cloud Folder?.
        /// </summary>
        public static string folderExitTextFieldHeader {
            get {
                return ResourceManager.GetString("folderExitTextFieldHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Exists!.
        /// </summary>
        public static string folderExitTextFieldTitle {
            get {
                return ResourceManager.GetString("folderExitTextFieldTitle", resourceCulture);
            }
        }
    }
}
