//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudApiPrivate.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudApiPrivate.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the contents of the Cloud folder..
        /// </summary>
        public static string CloudFolderIconDescription {
            get {
                return ResourceManager.GetString("CloudFolderIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     &apos;
        ///    &apos;  PinToTaskbar.vbs
        ///    &apos;  Cloud Windows
        ///    &apos;
        ///    &apos;  Created by BobS.
        ///    &apos;  Copyright (c) Cloud.com. All rights reserved.
        ///    &apos;
        ///    &apos;  Mostly from: http://wayneye.wordpress.com/2010/07/17/programmatically-pin-shortcut-onto-taskbar-on-win7/
        ///    &apos;
        ///    &apos; Parameter: The full path to the user&apos;s Desktop folder.
        ///    &apos; Parameter: The name of the shortcut file in the user&apos;s Desktop folder (without the extension).
        ///    &apos; Call as &quot;C:\Windows\SysWOW64\cscript.exe&quot; //B //T:30 //Nologo &quot;&lt;path to thi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PinToTaskBar {
            get {
                return ResourceManager.GetString("PinToTaskBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP.
        /// </summary>
        public static string useProxyHTTP {
            get {
                return ResourceManager.GetString("useProxyHTTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS4.
        /// </summary>
        public static string useProxySOCK4 {
            get {
                return ResourceManager.GetString("useProxySOCK4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS5.
        /// </summary>
        public static string useProxySOCK5 {
            get {
                return ResourceManager.GetString("useProxySOCK5", resourceCulture);
            }
        }
    }
}
