
      //FileCreation.xsd and resulting generated code
      //Cloud
      
      //Created by DavidBruck.
      
      //Copyright (c) Cloud.com. All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace CloudTests.FileCreation {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Cloud.com/FileCreation.xsd")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://Cloud.com/FileCreation.xsd", IsNullable=false)]
    public partial class FileCreation {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Copyright", typeof(Copyright))]
        [System.Xml.Serialization.XmlElementAttribute("ParallelFileOperationSet", typeof(ParallelFileOperationSet))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Cloud.com/FileCreation.xsd")]
    public partial class Copyright {
        
        private string fileNameField;
        
        private CopyrightCopyright copyright1Field;
        
        private string creatorField;
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Copyright")]
        public CopyrightCopyright Copyright1 {
            get {
                return this.copyright1Field;
            }
            set {
                this.copyright1Field = value;
            }
        }
        
        /// <remarks/>
        public string Creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Cloud.com/FileCreation.xsd")]
    public enum CopyrightCopyright {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Implementation of FileCreation.xsd XML Schema. Cloud. Copyright (c) Cloud.com. Al" +
            "l rights reserved.")]
        ImplementationofFileCreationxsdXMLSchemaCloudCopyrightcCloudcomAllrightsreserved,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Cloud.com/FileCreation.xsd")]
    public partial class ParallelFileOperationSet {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SingleFileOperation", typeof(SingleFileOperation))]
        [System.Xml.Serialization.XmlElementAttribute("Sleep", typeof(int))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Cloud.com/FileCreation.xsd")]
    public partial class SingleFileOperation {
        
        private string newRelativePathField;
        
        private string oldRelativePathField;
        
        private bool isFolderField;
        
        private FileOperationType typeField;
        
        private ChangedData dataField;
        
        private uint streamIterationsField;
        
        private bool streamIterationsFieldSpecified;
        
        private uint millisecondDelayBetweenStreamIterationsField;
        
        private bool millisecondDelayBetweenStreamIterationsFieldSpecified;
        
        private bool waitOnStreamCompletionField;
        
        private bool waitOnStreamCompletionFieldSpecified;
        
        private int minimumWaitOnLockedModifyField;
        
        private bool minimumWaitOnLockedModifyFieldSpecified;
        
        /// <remarks/>
        public string NewRelativePath {
            get {
                return this.newRelativePathField;
            }
            set {
                this.newRelativePathField = value;
            }
        }
        
        /// <remarks/>
        public string OldRelativePath {
            get {
                return this.oldRelativePathField;
            }
            set {
                this.oldRelativePathField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFolder {
            get {
                return this.isFolderField;
            }
            set {
                this.isFolderField = value;
            }
        }
        
        /// <remarks/>
        public FileOperationType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public ChangedData Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public uint StreamIterations {
            get {
                return this.streamIterationsField;
            }
            set {
                this.streamIterationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StreamIterationsSpecified {
            get {
                return this.streamIterationsFieldSpecified;
            }
            set {
                this.streamIterationsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public uint MillisecondDelayBetweenStreamIterations {
            get {
                return this.millisecondDelayBetweenStreamIterationsField;
            }
            set {
                this.millisecondDelayBetweenStreamIterationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MillisecondDelayBetweenStreamIterationsSpecified {
            get {
                return this.millisecondDelayBetweenStreamIterationsFieldSpecified;
            }
            set {
                this.millisecondDelayBetweenStreamIterationsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool WaitOnStreamCompletion {
            get {
                return this.waitOnStreamCompletionField;
            }
            set {
                this.waitOnStreamCompletionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WaitOnStreamCompletionSpecified {
            get {
                return this.waitOnStreamCompletionFieldSpecified;
            }
            set {
                this.waitOnStreamCompletionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int MinimumWaitOnLockedModify {
            get {
                return this.minimumWaitOnLockedModifyField;
            }
            set {
                this.minimumWaitOnLockedModifyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimumWaitOnLockedModifySpecified {
            get {
                return this.minimumWaitOnLockedModifyFieldSpecified;
            }
            set {
                this.minimumWaitOnLockedModifyFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Cloud.com/FileCreation.xsd")]
    public enum FileOperationType {
        
        /// <remarks/>
        Create,
        
        /// <remarks/>
        Rename,
        
        /// <remarks/>
        Delete,
        
        /// <remarks/>
        LockedModify,
        
        /// <remarks/>
        UnlockedAppend,
        
        /// <remarks/>
        Stream,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Cloud.com/FileCreation.xsd")]
    public partial class ChangedData {
        
        private uint sizeDeltaField;
        
        private bool sizeDeltaFieldSpecified;
        
        private string specificDataField;
        
        /// <remarks/>
        public uint SizeDelta {
            get {
                return this.sizeDeltaField;
            }
            set {
                this.sizeDeltaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SizeDeltaSpecified {
            get {
                return this.sizeDeltaFieldSpecified;
            }
            set {
                this.sizeDeltaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string SpecificData {
            get {
                return this.specificDataField;
            }
            set {
                this.specificDataField = value;
            }
        }
    }
}
