//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLIndexer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnumCategory
    {
        public EnumCategory()
        {
            this.Enums = new HashSet<SQLEnum>();
        }
    
        public int EnumCategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SQLEnum> Enums { get; set; }
    }
}
