//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLIndexer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSystemObject
    {
        public FileSystemObject()
        {
            this.Events = new HashSet<Event>();
            this.SyncStates = new HashSet<SyncState>();
            this.ServerLinkedSyncStates = new HashSet<SyncState>();
        }
    
        public long FileSystemObjectId { get; set; }
        public string Path { get; set; }
        public Nullable<System.DateTime> LastTime { get; set; }
        public Nullable<System.DateTime> CreationTime { get; set; }
        public bool IsFolder { get; set; }
        public Nullable<long> Size { get; set; }
        public string TargetPath { get; set; }
        public int PathChecksum { get; set; }
        public string Revision { get; set; }
        public string StorageKey { get; set; }
        public bool RevisionIsNull { get; set; }
    
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<SyncState> SyncStates { get; set; }
        public virtual ICollection<SyncState> ServerLinkedSyncStates { get; set; }
    }
}
