//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLIndexer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IndexDBEntities : DbContext
    {
        public IndexDBEntities()
            : base("name=IndexDBEntities")
        {
        }
    	
        public IndexDBEntities(string connectionString)
            : base(connectionString)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EnumCategory> EnumCategories { get; set; }
        public DbSet<SQLEnum> SQLEnums { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<FileSystemObject> FileSystemObjects { get; set; }
        public DbSet<Sync> Syncs { get; set; }
        public DbSet<SyncState> SyncStates { get; set; }
        public DbSet<Version> Versions { get; set; }
    }
}
