//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLIndexer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SQLEnum
    {
        public SQLEnum()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int EnumId { get; set; }
        public int EnumCategoryId { get; set; }
        public string Name { get; set; }
    
        public virtual EnumCategory EnumCategory { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
