//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudApiPublic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CloudApiPublic.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  We&apos;re sorry, it seems that something went wrong while requesting status from the server..
        /// </summary>
        internal static string ErrorPostingSyncFromServer {
            get {
                return ResourceManager.GetString("ErrorPostingSyncFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  We&apos;re sorry, it seems that something went wrong while syncing files to the server..
        /// </summary>
        internal static string ErrorPostingSyncToServer {
            get {
                return ResourceManager.GetString("ErrorPostingSyncToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  We&apos;re sorry, it seems that something when wrong while starting a server file upload or download. .
        /// </summary>
        internal static string ErrorPuttingUploadOrDownloadToServer {
            get {
                return ResourceManager.GetString("ErrorPuttingUploadOrDownloadToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while creating your account.  The error code is {0}..
        /// </summary>
        internal static string ExceptionCreatingUserRegistrationWithCode {
            get {
                return ResourceManager.GetString("ExceptionCreatingUserRegistrationWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while logging into your account.  The error code is {0}..
        /// </summary>
        internal static string ExceptionLoggingInWithCode {
            get {
                return ResourceManager.GetString("ExceptionLoggingInWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while removing this device from your account..
        /// </summary>
        internal static string ExceptionUnlinking {
            get {
                return ResourceManager.GetString("ExceptionUnlinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while removing this device from your account.  The error code is {0}..
        /// </summary>
        internal static string ExceptionUnlinkingWithCode {
            get {
                return ResourceManager.GetString("ExceptionUnlinkingWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits.
        /// </summary>
        internal static string OsBits {
            get {
                return ResourceManager.GetString("OsBits", resourceCulture);
            }
        }
    }
}
