//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Static {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloud.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string AbbreviatedGigabytes {
            get {
                return ResourceManager.GetString("AbbreviatedGigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string AbbreviatedKilobytes {
            get {
                return ResourceManager.GetString("AbbreviatedKilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string AbbreviatedMegabytes {
            get {
                return ResourceManager.GetString("AbbreviatedMegabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData.
        /// </summary>
        internal static string AppDataFolderNameVista {
            get {
                return ResourceManager.GetString("AppDataFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string BytesPlural {
            get {
                return ResourceManager.GetString("BytesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        internal static string BytesSingular {
            get {
                return ResourceManager.GetString("BytesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : cancelled---.
        /// </summary>
        internal static string CancelledHttpResponseAppend {
            get {
                return ResourceManager.GetString("CancelledHttpResponseAppend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgramData\Microsoft\Windows.
        /// </summary>
        internal static string CommonStartMenuParentFolderNameVista {
            get {
                return ResourceManager.GetString("CommonStartMenuParentFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents and Settings\All Users.
        /// </summary>
        internal static string CommonStartMenuParentFolderNameXP {
            get {
                return ResourceManager.GetString("CommonStartMenuParentFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---File upload complete---.
        /// </summary>
        internal static string CompleteFileUpload {
            get {
                return ResourceManager.GetString("CompleteFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string DocumentsAndSettingsVista {
            get {
                return ResourceManager.GetString("DocumentsAndSettingsVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents and Settings.
        /// </summary>
        internal static string DocumentsAndSettingsXP {
            get {
                return ResourceManager.GetString("DocumentsAndSettingsXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string DocumentsFolderNameVista {
            get {
                return ResourceManager.GetString("DocumentsFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        internal static string DocumentsFolderNameXP {
            get {
                return ResourceManager.GetString("DocumentsFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  We&apos;re sorry, it seems that something went wrong while requesting status from the server..
        /// </summary>
        internal static string ErrorPostingSyncFromServer {
            get {
                return ResourceManager.GetString("ErrorPostingSyncFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  We&apos;re sorry, it seems that something went wrong while syncing files to the server..
        /// </summary>
        internal static string ErrorPostingSyncToServer {
            get {
                return ResourceManager.GetString("ErrorPostingSyncToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  We&apos;re sorry, it seems that something when wrong while starting a server file upload or download. .
        /// </summary>
        internal static string ErrorPuttingUploadOrDownloadToServer {
            get {
                return ResourceManager.GetString("ErrorPuttingUploadOrDownloadToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while creating your account.  The error code is {0}..
        /// </summary>
        internal static string ExceptionCreatingUserRegistrationWithCode {
            get {
                return ResourceManager.GetString("ExceptionCreatingUserRegistrationWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delegateToWrap cannot be processed when null.
        /// </summary>
        internal static string ExceptionDelegateAndDataHolderNullDelegateToWrap {
            get {
                return ResourceManager.GetString("ExceptionDelegateAndDataHolderNullDelegateToWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 must be 128 bits (a byte array of length 16).
        /// </summary>
        internal static string ExceptionFileChangeSetMD5ByteLength {
            get {
                return ResourceManager.GetString("ExceptionFileChangeSetMD5ByteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendBackChange cannot be null.
        /// </summary>
        internal static string ExceptionFileChangeUpDownEventArgsNullSendBackChange {
            get {
                return ResourceManager.GetString("ExceptionFileChangeUpDownEventArgsNullSendBackChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MakeAsyncRequestSynchronous was processed without param1.
        /// </summary>
        internal static string ExceptionHelpersAsyncGetUploadRequestStreamOrDownloadResponseMakeSyncParam1 {
            get {
                return ResourceManager.GetString("ExceptionHelpersAsyncGetUploadRequestStreamOrDownloadResponseMakeSyncParam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rootPathObject must start with a upper-case drive letter.
        /// </summary>
        internal static string ExceptionHelpersCheckForBadPathDriveLetter {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckForBadPathDriveLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rootPathObject root drive letter represents an invalid DriveType: {0}.
        /// </summary>
        internal static string ExceptionHelpersCheckForBadPathDriveType {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckForBadPathDriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rootPathObject cannot have an empty directory name for any directory in the parent path hierarchy and cannot have a trailing slash.
        /// </summary>
        internal static string ExceptionHelpersCheckForBadPathEmptyDirectory {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckForBadPathEmptyDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rootPathObject must start at a drive letter and have a proceeding trailing slash.
        /// </summary>
        internal static string ExceptionHelpersCheckForBadPathProceedingSlash {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckForBadPathProceedingSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraceCategory must not be null.
        /// </summary>
        internal static string ExceptionHelpersCheckLogFileExistanceTraceCategoryNull {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckLogFileExistanceTraceCategoryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncbox path is too long by {0} characters.
        /// </summary>
        internal static string ExceptionHelpersCheckSyncRootLengthTooLongPlural {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckSyncRootLengthTooLongPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncbox path is too long by {0} character.
        /// </summary>
        internal static string ExceptionHelpersCheckSyncRootLengthTooLongSingular {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckSyncRootLengthTooLongSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve property values on an invalid DictionaryTryGetValueResult.
        /// </summary>
        internal static string ExceptionHelpersDictionaryTryGetValueResultInvalid {
            get {
                return ResourceManager.GetString("ExceptionHelpersDictionaryTryGetValueResultInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eventSource cannot be null.
        /// </summary>
        internal static string ExceptionHelpersHandleUploadDownloadStatusNullEventSource {
            get {
                return ResourceManager.GetString("ExceptionHelpersHandleUploadDownloadStatusNullEventSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hashString must be in a hexadecimal string format with no seperator characters and two characters per byte.
        /// </summary>
        internal static string ExceptionHelpersParseHexadecimalStringToByteArrayHashStringFormat {
            get {
                return ResourceManager.GetString("ExceptionHelpersParseHexadecimalStringToByteArrayHashStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot do anything with the Cloud SDK if Helpers.AllHaltedOnUnrecoverableError is set.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerAllHaltedOnUnrecoverableError {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerAllHaltedOnUnrecoverableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled by client.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerClientCancelled {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerClientCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download httpRequest EndGetResponse threw a WebException without a WebResponse.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerDownloadNullResponse {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerDownloadNullResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting request stream for a download.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerDownloadRequestStream {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerDownloadRequestStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to httpResponse GetResponse at URL {0}, MethodPath {1} threw a WebException without a WebResponse.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerGeneralNullResponse {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerGeneralNullResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {missing serverMethodPath}.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerGeneralNullResponseNullServerMethodPath {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerGeneralNullResponseNullServerMethodPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {missing serverUrl}.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerGeneralNullResponseNullServerUrl {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerGeneralNullResponseNullServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting request stream for a post operation.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerGeneralRequestStream {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerGeneralRequestStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown method: {0}.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerHttpMethod {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerHttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HTTP response status code at URL {0}, MethodPath {1}.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerInvalidResponseStatus {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerInvalidResponseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read the response stream.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerInvalidStatusStreamRead {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerInvalidStatusStreamRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find serializer for JsonContracts.AuthenticationErrorResponse in SerializableResponseTypes.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerMissingAuthenticationErrorResponse {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerMissingAuthenticationErrorResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to httpRequest cannot be null.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerNullHttpRequest {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerNullHttpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown requestContent Type: {0}.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerRequestContentType {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerRequestContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized JsonObject null from requestString.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerRequestStringJsonObject {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerRequestStringJsonObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to deserialize response stream and missed an earlier check for this condition.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerResponseDeserializeMissedEarlierCheck {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerResponseDeserializeMissedEarlierCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deserialized JsonObject null from responseString.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerResponseStringJsonObject {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerResponseStringJsonObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploadDownload TempDownloadFolderPath cannot be null.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerTempDownloadFolderPath {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerTempDownloadFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uploadDownload must be either upload or download.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerUploadDownloadType {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerUploadDownloadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error getting request stream for an upload.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpInnerUploadRequestStream {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpInnerUploadRequestStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestNewCredentialsInfo GetCurrentCredentialsCallback must not be null.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpNullGetCurrentCredentialsCallback {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpNullGetCurrentCredentialsCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestNewCredentialsInfo ProcessingStateByThreadId must not be null.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpNullProcessingStateByThreadId {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpNullProcessingStateByThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestNewCredentialsInfo must not be null.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpNullRequestNewCredentialsInfo {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpNullRequestNewCredentialsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestNewCredentialsInfo SetNewCredentialsCallback must not be null.
        /// </summary>
        internal static string ExceptionHelpersProcessHttpNullSetNewCredentialsCallback {
            get {
                return ResourceManager.GetString("ExceptionHelpersProcessHttpNullSetNewCredentialsCallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed all retries with a numRetries of {0}.
        /// </summary>
        internal static string ExceptionHelpersRunActionWithRetriesFailedRetries {
            get {
                return ResourceManager.GetString("ExceptionHelpersRunActionWithRetriesFailedRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toRun cannot be null.
        /// </summary>
        internal static string ExceptionHelpersRunActionWithRetriesNullToRun {
            get {
                return ResourceManager.GetString("ExceptionHelpersRunActionWithRetriesNullToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ListRemoveAllEnumerator has already been disposed.
        /// </summary>
        internal static string ExceptionListRemoveAllEnumeratorDisposed {
            get {
                return ResourceManager.GetString("ExceptionListRemoveAllEnumeratorDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset not supported.
        /// </summary>
        internal static string ExceptionListRemoveAllEnumeratorReset {
            get {
                return ResourceManager.GetString("ExceptionListRemoveAllEnumeratorReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while logging into your account.  The error code is {0}..
        /// </summary>
        internal static string ExceptionLoggingInWithCode {
            get {
                return ResourceManager.GetString("ExceptionLoggingInWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while removing this device from your account..
        /// </summary>
        internal static string ExceptionUnlinking {
            get {
                return ResourceManager.GetString("ExceptionUnlinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while removing this device from your account.  The error code is {0}..
        /// </summary>
        internal static string ExceptionUnlinkingWithCode {
            get {
                return ResourceManager.GetString("ExceptionUnlinkingWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Incomplete file download---.
        /// </summary>
        internal static string IncompleteFileDownload {
            get {
                return ResourceManager.GetString("IncompleteFileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData\Local.
        /// </summary>
        internal static string LocalAppDataFolderNameVista {
            get {
                return ResourceManager.GetString("LocalAppDataFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Settings\Application Data.
        /// </summary>
        internal static string LocalAppDataFolderNameXP {
            get {
                return ResourceManager.GetString("LocalAppDataFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud exception type: {0}.
        /// </summary>
        internal static string LogCloudExceptionType {
            get {
                return ResourceManager.GetString("LogCloudExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http response:{0}{1}.
        /// </summary>
        internal static string LogHttpResponse {
            get {
                return ResourceManager.GetString("LogHttpResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http status code: {0}.
        /// </summary>
        internal static string LogHttpStatus {
            get {
                return ResourceManager.GetString("LogHttpStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StackTrace:{0}{1}.
        /// </summary>
        internal static string LogStacktrace {
            get {
                return ResourceManager.GetString("LogStacktrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string MusicFolderNameVista {
            get {
                return ResourceManager.GetString("MusicFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Music.
        /// </summary>
        internal static string MusicFolderNameXP {
            get {
                return ResourceManager.GetString("MusicFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PossiblyUnmanagedCode.
        /// </summary>
        internal static string NoSpacesHelpersGetDefaultNameFromApplicationNameDefault {
            get {
                return ResourceManager.GetString("NoSpacesHelpersGetDefaultNameFromApplicationNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppDataFolderNameVista.
        /// </summary>
        internal static string NotTranslatedAppDataFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedAppDataFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace-????-??-??-.
        /// </summary>
        internal static string NotTranslatedCheckLogFileExistanceSearchStart {
            get {
                return ResourceManager.GetString("NotTranslatedCheckLogFileExistanceSearchStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *..
        /// </summary>
        internal static string NotTranslatedCheckLogFileExistanceStarDot {
            get {
                return ResourceManager.GetString("NotTranslatedCheckLogFileExistanceStarDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace-.
        /// </summary>
        internal static string NotTranslatedCheckLogFileExistanceTrace {
            get {
                return ResourceManager.GetString("NotTranslatedCheckLogFileExistanceTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd-.
        /// </summary>
        internal static string NotTranslatedCheckLogFileExistanceYearMonthDay {
            get {
                return ResourceManager.GetString("NotTranslatedCheckLogFileExistanceYearMonthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonStartMenuParentFolderNameVista.
        /// </summary>
        internal static string NotTranslatedCommonStartMenuParentFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedCommonStartMenuParentFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonStartMenuParentFolderNameXP.
        /// </summary>
        internal static string NotTranslatedCommonStartMenuParentFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedCommonStartMenuParentFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentsAndSettingsVista.
        /// </summary>
        internal static string NotTranslatedDocumentsAndSettingsVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedDocumentsAndSettingsVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentsAndSettingsXP.
        /// </summary>
        internal static string NotTranslatedDocumentsAndSettingsXPName {
            get {
                return ResourceManager.GetString("NotTranslatedDocumentsAndSettingsXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentsFolderNameVista.
        /// </summary>
        internal static string NotTranslatedDocumentsFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedDocumentsFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentsFolderNameXP.
        /// </summary>
        internal static string NotTranslatedDocumentsFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedDocumentsFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op_Explicit.
        /// </summary>
        internal static string NotTranslatedExplicitOperator {
            get {
                return ResourceManager.GetString("NotTranslatedExplicitOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-z]:\\$.
        /// </summary>
        internal static string NotTranslatedHelpersCheckForBadPathDriveLetterRegex {
            get {
                return ResourceManager.GetString("NotTranslatedHelpersCheckForBadPathDriveLetterRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:##.##} {1}.
        /// </summary>
        internal static string NotTranslatedHelpersFormatBytesString {
            get {
                return ResourceManager.GetString("NotTranslatedHelpersFormatBytesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertTo.
        /// </summary>
        internal static string NotTranslatedHelpersMethodInfoConvertTo {
            get {
                return ResourceManager.GetString("NotTranslatedHelpersMethodInfoConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultForType.
        /// </summary>
        internal static string NotTranslatedHelpersMethodInfoDefaultForType {
            get {
                return ResourceManager.GetString("NotTranslatedHelpersMethodInfoDefaultForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string NotTranslatedHttpClose {
            get {
                return ResourceManager.GetString("NotTranslatedHttpClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100-continue.
        /// </summary>
        internal static string NotTranslatedHttpContinue {
            get {
                return ResourceManager.GetString("NotTranslatedHttpContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep-Alive.
        /// </summary>
        internal static string NotTranslatedHttpKeepAlive {
            get {
                return ResourceManager.GetString("NotTranslatedHttpKeepAlive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op_Implicit.
        /// </summary>
        internal static string NotTranslatedImplicitOperator {
            get {
                return ResourceManager.GetString("NotTranslatedImplicitOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalAppDataFolderNameVista.
        /// </summary>
        internal static string NotTranslatedLocalAppDataFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedLocalAppDataFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalAppDataFolderNameXP.
        /// </summary>
        internal static string NotTranslatedLocalAppDataFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedLocalAppDataFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicFolderNameVista.
        /// </summary>
        internal static string NotTranslatedMusicFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedMusicFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicFolderNameXP.
        /// </summary>
        internal static string NotTranslatedMusicFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedMusicFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PicturesFolderNameVista.
        /// </summary>
        internal static string NotTranslatedPicturesFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedPicturesFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PicturesFolderNameXP.
        /// </summary>
        internal static string NotTranslatedPicturesFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedPicturesFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicUserNameVista.
        /// </summary>
        internal static string NotTranslatedPublicUserNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedPublicUserNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicUserNameXP.
        /// </summary>
        internal static string NotTranslatedPublicUserNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedPublicUserNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoamingAppDataFolderNameVista.
        /// </summary>
        internal static string NotTranslatedRoamingAppDataFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedRoamingAppDataFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoamingAppDataFolderNameXP.
        /// </summary>
        internal static string NotTranslatedRoamingAppDataFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedRoamingAppDataFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartMenuFolderNameVista.
        /// </summary>
        internal static string NotTranslatedStartMenuFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedStartMenuFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartMenuFolderNameXP.
        /// </summary>
        internal static string NotTranslatedStartMenuFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedStartMenuFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemDrive.
        /// </summary>
        internal static string NotTranslatedSystemDrive {
            get {
                return ResourceManager.GetString("NotTranslatedSystemDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.0.0.
        /// </summary>
        internal static string NotTranslatedZeroedVersion {
            get {
                return ResourceManager.GetString("NotTranslatedZeroedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---responseBody set to null---.
        /// </summary>
        internal static string NullHttpResponseBody {
            get {
                return ResourceManager.GetString("NullHttpResponseBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits.
        /// </summary>
        internal static string OsBits {
            get {
                return ResourceManager.GetString("OsBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string PicturesFolderNameVista {
            get {
                return ResourceManager.GetString("PicturesFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Pictures.
        /// </summary>
        internal static string PicturesFolderNameXP {
            get {
                return ResourceManager.GetString("PicturesFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string PublicUserNameVista {
            get {
                return ResourceManager.GetString("PublicUserNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        internal static string PublicUserNameXP {
            get {
                return ResourceManager.GetString("PublicUserNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData\Roaming.
        /// </summary>
        internal static string RoamingAppDataFolderNameVista {
            get {
                return ResourceManager.GetString("RoamingAppDataFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Data.
        /// </summary>
        internal static string RoamingAppDataFolderNameXP {
            get {
                return ResourceManager.GetString("RoamingAppDataFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---File upload started---.
        /// </summary>
        internal static string StartedFileUpload {
            get {
                return ResourceManager.GetString("StartedFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData\Roaming\Microsoft\Windows\Start Menu.
        /// </summary>
        internal static string StartMenuFolderNameVista {
            get {
                return ResourceManager.GetString("StartMenuFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Menu.
        /// </summary>
        internal static string StartMenuFolderNameXP {
            get {
                return ResourceManager.GetString("StartMenuFolderNameXP", resourceCulture);
            }
        }
    }
}
