//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cloud.Static {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cloud.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        internal static string AbbreviatedGigabytes {
            get {
                return ResourceManager.GetString("AbbreviatedGigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KB.
        /// </summary>
        internal static string AbbreviatedKilobytes {
            get {
                return ResourceManager.GetString("AbbreviatedKilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        internal static string AbbreviatedMegabytes {
            get {
                return ResourceManager.GetString("AbbreviatedMegabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData.
        /// </summary>
        internal static string AppDataFolderNameVista {
            get {
                return ResourceManager.GetString("AppDataFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string BytesPlural {
            get {
                return ResourceManager.GetString("BytesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        internal static string BytesSingular {
            get {
                return ResourceManager.GetString("BytesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aResult does not match expected internal type.
        /// </summary>
        internal static string CLCredentialaResultInternalTypeMismatch {
            get {
                return ResourceManager.GetString("CLCredentialaResultInternalTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast state as.
        /// </summary>
        internal static string CLCredentialCannotCastStateAs {
            get {
                return ResourceManager.GetString("CLCredentialCannotCastStateAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot do anything with the Cloud SDK if Helpers.AllHaltedOnUnrecoverableError is set.
        /// </summary>
        internal static string CLCredentialHelpersAllHaltedOnUnrecoverableErrorIsSet {
            get {
                return ResourceManager.GetString("CLCredentialHelpersAllHaltedOnUnrecoverableErrorIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key cannot be null.
        /// </summary>
        internal static string CLCredentialKeyCannotBeNull {
            get {
                return ResourceManager.GetString("CLCredentialKeyCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeoutMilliseconds must be greater than zero.
        /// </summary>
        internal static string CLCredentialMSTimeoutMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("CLCredentialMSTimeoutMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pushRequest must not be null.
        /// </summary>
        internal static string CLCredentialPushRequestCannotBeNull {
            get {
                return ResourceManager.GetString("CLCredentialPushRequestCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret cannot be null.
        /// </summary>
        internal static string CLCredentialSecretCannotBeNull {
            get {
                return ResourceManager.GetString("CLCredentialSecretCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCopy must not be null.
        /// </summary>
        internal static string CLCredentialSettingsToCopyNotBeNull {
            get {
                return ResourceManager.GetString("CLCredentialSettingsToCopyNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string CLCredentialStringSettingsN {
            get {
                return ResourceManager.GetString("CLCredentialStringSettingsN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncbox cannot be null.
        /// </summary>
        internal static string CLEngineSyncboxCannotBeNull {
            get {
                return ResourceManager.GetString("CLEngineSyncboxCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aResult does not match expected internal type.
        /// </summary>
        internal static string CLHttpRestaResultInternalTypeMismatch {
            get {
                return ResourceManager.GetString("CLHttpRestaResultInternalTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot cast state as.
        /// </summary>
        internal static string CLHttpRestCannotCastStateAs {
            get {
                return ResourceManager.GetString("CLHttpRestCannotCastStateAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletionChange Direction is not To the server.
        /// </summary>
        internal static string CLHttpRestChangeDirectionIsNotToServer {
            get {
                return ResourceManager.GetString("CLHttpRestChangeDirectionIsNotToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletionChange is not of Type Deletion.
        /// </summary>
        internal static string CLHttpRestChangeIsNotOfTypeDeletion {
            get {
                return ResourceManager.GetString("CLHttpRestChangeIsNotOfTypeDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCommunicate cannot be null.
        /// </summary>
        internal static string CLHttpRestCommunicateCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestCommunicateCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncbox.CopiedSettings must not be null.
        /// </summary>
        internal static string CLHttpRestCopiedSettingsMustNotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestCopiedSettingsMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to copyTargetPath cannot be null.
        /// </summary>
        internal static string CLHttpRestCopyPathCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestCopyPathCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Syncbox cannot be modified while in use in active syncing.
        /// </summary>
        internal static string CLHttpRestCurrentSyncboxCannotBeModifiedWhileSyncing {
            get {
                return ResourceManager.GetString("CLHttpRestCurrentSyncboxCannotBeModifiedWhileSyncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletionChange cannot be null.
        /// </summary>
        internal static string CLHttpRestDeletionChangeCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestDeletionChangeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletionChange Metadata ServerId must not be null.
        /// </summary>
        internal static string CLHttpRestDeletionChangeMetadataServerIDMustnotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestDeletionChangeMetadataServerIDMustnotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings DeviceId cannot be null.
        /// </summary>
        internal static string CLHttpRestDeviceIDCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestDeviceIDCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path for temp download files is too long by.
        /// </summary>
        internal static string CLHttpRestFolderPathTooLong {
            get {
                return ResourceManager.GetString("CLHttpRestFolderPathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friendlyName must be specified.
        /// </summary>
        internal static string CLHttpRestFriendlyNameNotSpecified {
            get {
                return ResourceManager.GetString("CLHttpRestFriendlyNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fullPath is not in the proper format.
        /// </summary>
        internal static string CLHttpRestFullPathBadFormat {
            get {
                return ResourceManager.GetString("CLHttpRestFullPathBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fullPath does not contain settings SyncRoot.
        /// </summary>
        internal static string CLHttpRestFullPathDoesNotContainSettingsSyncRoot {
            get {
                return ResourceManager.GetString("CLHttpRestFullPathDoesNotContainSettingsSyncRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both fullPath and serverId cannot be null, at least one is required.
        /// </summary>
        internal static string CLHttpRestFullPathorServerIDRequired {
            get {
                return ResourceManager.GetString("CLHttpRestFullPathorServerIDRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an internal error attempting to retrieve the progress, Error 1.
        /// </summary>
        internal static string CLHttpRestInternalPRogressRetreivalFailure1 {
            get {
                return ResourceManager.GetString("CLHttpRestInternalPRogressRetreivalFailure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an internal error attempting to retrieve the progress, Error 2.
        /// </summary>
        internal static string CLHttpRestInternalPRogressRetreivalFailure2 {
            get {
                return ResourceManager.GetString("CLHttpRestInternalPRogressRetreivalFailure2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 lowercase string retrieved from Resources.CLHttpRestCommunicateCannotBeNull, set via toCommunicate.SetMD5.
        /// </summary>
        internal static string CLHttpRestMD5LowerCaseStringSet {
            get {
                return ResourceManager.GetString("CLHttpRestMD5LowerCaseStringSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deletionChange Metadata cannot be null.
        /// </summary>
        internal static string CLHttpRestMetadataCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestMetadataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCommunicate Metadata HashableProperties Size cannot be null.
        /// </summary>
        internal static string CLHttpRestMetadataHashablePropertiesSizeCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestMetadataHashablePropertiesSizeCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCommunicate Metadata Revision cannot be null.
        /// </summary>
        internal static string CLHttpRestMetaDataRevisionCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestMetaDataRevisionCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCommunicate NewPath cannot be null.
        /// </summary>
        internal static string CLHttpRestNewPathCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestNewPathCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCommunicate OldPath cannot be null.
        /// </summary>
        internal static string CLHttpRestOldPathCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestOldPathCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to planId must not be zero.
        /// </summary>
        internal static string CLHttpRestPlanIDCannotBeZero {
            get {
                return ResourceManager.GetString("CLHttpRestPlanIDCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pushRequest must not be null.
        /// </summary>
        internal static string CLHttpRestPushRequestMustNotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestPushRequestMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncbox Credential cannot be null.
        /// </summary>
        internal static string CLHttpRestsyncboxCredentialCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestsyncboxCredentialCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncbox must not be null.
        /// </summary>
        internal static string CLHttpRestSyncboxMustNotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestSyncboxMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings SyncRoot represents a bad path.
        /// </summary>
        internal static string CLHttpRestSyncRootBadPath {
            get {
                return ResourceManager.GetString("CLHttpRestSyncRootBadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings SyncRoot cannot be null.
        /// </summary>
        internal static string CLHttpRestSyncRootCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestSyncRootCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncToRequest must not be null.
        /// </summary>
        internal static string CLHttpRestSyncToRequestMustNotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestSyncToRequestMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customDownloadFolderFullPath is bad.
        /// </summary>
        internal static string CLHttpRestThecustomDownloadFolderFullPathIsBad {
            get {
                return ResourceManager.GetString("CLHttpRestThecustomDownloadFolderFullPathIsBad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timeoutMilliseconds must be greater than zero.
        /// </summary>
        internal static string CLHttpRestTimeoutMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("CLHttpRestTimeoutMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCommunicate cannot be both a folder and of type Modified.
        /// </summary>
        internal static string CLHttpRestToCommunicateCannotBeFolderandModified {
            get {
                return ResourceManager.GetString("CLHttpRestToCommunicateCannotBeFolderandModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCommunicate Direction is not To the server.
        /// </summary>
        internal static string CLHttpRestToCommunicateDirectionisNotToServer {
            get {
                return ResourceManager.GetString("CLHttpRestToCommunicateDirectionisNotToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCommunicate Metadata cannot be null.
        /// </summary>
        internal static string CLHttpRestToCommunicateMetedataCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestToCommunicateMetedataCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCommunicate Type is an unknown FileChangeType: .
        /// </summary>
        internal static string CLHttpRestToCommunicateTypeIsUnknownFileChangeType {
            get {
                return ResourceManager.GetString("CLHttpRestToCommunicateTypeIsUnknownFileChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either toCommunicate NewPath must not be null or toCommunicate Metadata ServerId must not be null or both must not be null.
        /// </summary>
        internal static string CLHttpRestXORNewPathServerIDCannotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestXORNewPathServerIDCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either pathToFile must not be null or fileServerId must not be null or both must not be null.
        /// </summary>
        internal static string CLHttpRestXORPathtoFileFileServerIDMustNotBeNull {
            get {
                return ResourceManager.GetString("CLHttpRestXORPathtoFileFileServerIDMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot do anything with the Cloud SDK if Helpers.AllHaltedOnUnrecoverableError is set.
        /// </summary>
        internal static string CLSyncBoxAllHaltedOnUnrecoverableErrorIsSet {
            get {
                return ResourceManager.GetString("CLSyncBoxAllHaltedOnUnrecoverableErrorIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncbox: Constructing....
        /// </summary>
        internal static string CLSyncBoxConstructing {
            get {
                return ResourceManager.GetString("CLSyncBoxConstructing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncbox: Construction: ERROR: {0}..
        /// </summary>
        internal static string CLSyncboxConstructionError0 {
            get {
                return ResourceManager.GetString("CLSyncboxConstructionError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncbox: Construction: ERROR: Msg: {0}..
        /// </summary>
        internal static string CLSyncBoxConstructionErrorMsg0 {
            get {
                return ResourceManager.GetString("CLSyncBoxConstructionErrorMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncbox: Construction: ERROR: Msg: {0}. Code: {1}..
        /// </summary>
        internal static string CLSyncBoxConstructionErrorMsg0Code1 {
            get {
                return ResourceManager.GetString("CLSyncBoxConstructionErrorMsg0Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating REST HTTP client.
        /// </summary>
        internal static string CLSyncBoxErrorCreatingRestHTTPClient {
            get {
                return ResourceManager.GetString("CLSyncBoxErrorCreatingRestHTTPClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error creating HTTP REST client.
        /// </summary>
        internal static string CLSyncBoxErrorUnknownErrorCreatingRestClient {
            get {
                return ResourceManager.GetString("CLSyncBoxErrorUnknownErrorCreatingRestClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncbox: Start: Create rest client..
        /// </summary>
        internal static string CLSyncBoxStartCreateRestClient {
            get {
                return ResourceManager.GetString("CLSyncBoxStartCreateRestClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: OnNotificationPerformManualSyncFrom: Send a Perform Manual SyncFrom to monitor..
        /// </summary>
        internal static string CLSynceEngineOnNotificationPerformManualSyncFrom {
            get {
                return ResourceManager.GetString("CLSynceEngineOnNotificationPerformManualSyncFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already started.
        /// </summary>
        internal static string CLSyncEngineAlreadyStarted {
            get {
                return ResourceManager.GetString("CLSyncEngineAlreadyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudRoot in settings represents a path which cannot be queried, check it first via Helpers.DirectoryMatchesCaseWithDisk.
        /// </summary>
        internal static string CLSyncEngineCloudRootRepresentsAPathThatCannotBeQueried {
            get {
                return ResourceManager.GetString("CLSyncEngineCloudRootRepresentsAPathThatCannotBeQueried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudRoot in settings represents a bad path, check it first via Helpers.CheckForBadPath.
        /// </summary>
        internal static string CLSyncEngineCloudRootRepsBadPath {
            get {
                return ResourceManager.GetString("CLSyncEngineCloudRootRepsBadPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CloudRoot in settings is too long, check it first via Helpers.CheckSyncRootLength.
        /// </summary>
        internal static string CLSyncEngineCloudRootSettingsTooLong {
            get {
                return ResourceManager.GetString("CLSyncEngineCloudRootSettingsTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ERROR: {0}..
        /// </summary>
        internal static string CLSyncEngineError0 {
            get {
                return ResourceManager.GetString("CLSyncEngineError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ERROR: BadCase (1). {0}..
        /// </summary>
        internal static string CLSyncEngineErrorBadCase {
            get {
                return ResourceManager.GetString("CLSyncEngineErrorBadCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: ERROR: Exception(2). Msg: {0}. Code: {1}..
        /// </summary>
        internal static string CLSyncEngineErrorException2Msg0Code1 {
            get {
                return ResourceManager.GetString("CLSyncEngineErrorException2Msg0Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred starting push notification.
        /// </summary>
        internal static string CLSyncEngineErrorOccurredStarrtingNotification {
            get {
                return ResourceManager.GetString("CLSyncEngineErrorOccurredStarrtingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: ERROR: Starting the initial indexing.  Msg: &lt;{0}&gt;. Code: {1}..
        /// </summary>
        internal static string CLSyncEngineErrorStartingInitialIndexingMsg0Code1 {
            get {
                return ResourceManager.GetString("CLSyncEngineErrorStartingInitialIndexingMsg0Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: ERROR: Starting the MonitorAgent.  Msg: &lt;{0}&gt;. Code: {1}..
        /// </summary>
        internal static string CLSyncEngineErrorStartingMonitorAgentMsg0Code1 {
            get {
                return ResourceManager.GetString("CLSyncEngineErrorStartingMonitorAgentMsg0Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting push notification.
        /// </summary>
        internal static string CLSyncEngineErrorStartingNotification {
            get {
                return ResourceManager.GetString("CLSyncEngineErrorStartingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: ERROR: Exception(5).  Msg: &lt;{0}&gt;..
        /// </summary>
        internal static string CLSyncEngineException5Msg0 {
            get {
                return ResourceManager.GetString("CLSyncEngineException5Msg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: ERROR: Exception(6).  Msg: &lt;{0}&gt;..
        /// </summary>
        internal static string CLSyncEngineException6Msg0 {
            get {
                return ResourceManager.GetString("CLSyncEngineException6Msg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ReleaseResources: File monitor stopped..
        /// </summary>
        internal static string CLSyncEngineFileMonitorStopped {
            get {
                return ResourceManager.GetString("CLSyncEngineFileMonitorStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot do anything with the Cloud SDK if Helpers.AllHaltedOnUnrecoverableError is set.
        /// </summary>
        internal static string CLSyncEngineHelpersAllHaltedOnUnrecoverableErrorIsSet {
            get {
                return ResourceManager.GetString("CLSyncEngineHelpersAllHaltedOnUnrecoverableErrorIsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indexer cannot be null.
        /// </summary>
        internal static string CLSyncEngineIndexerCannotBeNull {
            get {
                return ResourceManager.GetString("CLSyncEngineIndexerCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor cannot be null.
        /// </summary>
        internal static string CLSyncEngineMonitorCannotBeNull {
            get {
                return ResourceManager.GetString("CLSyncEngineMonitorCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: OnConnectionError: Entry. ERROR: Manual poll error: &lt;{0}&gt;. Web socket error: &lt;{1}&gt;..
        /// </summary>
        internal static string CLSyncEngineOnConnectionErrorEntryErrorManualPollErrorWebSocketError {
            get {
                return ResourceManager.GetString("CLSyncEngineOnConnectionErrorEntryErrorManualPollErrorWebSocketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: OnConnectionError: Notify the application..
        /// </summary>
        internal static string CLSyncEngineOnConnectionErrorNotifyApplication {
            get {
                return ResourceManager.GetString("CLSyncEngineOnConnectionErrorNotifyApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ReleaseResources: Disconnect PushNotificationServer..
        /// </summary>
        internal static string CLSyncEngineReleaseResourcesDisconnectPushNotificationServer {
            get {
                return ResourceManager.GetString("CLSyncEngineReleaseResourcesDisconnectPushNotificationServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ReleaseResources: IconOverlay stopped..
        /// </summary>
        internal static string CLSyncEngineReleaseResourcesIconOverlayStopped {
            get {
                return ResourceManager.GetString("CLSyncEngineReleaseResourcesIconOverlayStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ReleaseResources: Indexer stopped..
        /// </summary>
        internal static string CLsyncEngineReleaseResourcesIndexerStopped {
            get {
                return ResourceManager.GetString("CLsyncEngineReleaseResourcesIndexerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ReleaseResources: PushNotificationServer disconnected..
        /// </summary>
        internal static string CLSyncEngineReleaseResourcesPushNotificationServerDisconnected {
            get {
                return ResourceManager.GetString("CLSyncEngineReleaseResourcesPushNotificationServerDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ReleaseResources: Stop the file monitor..
        /// </summary>
        internal static string CLSyncEngineReleaseResourcesStopFileMonitor {
            get {
                return ResourceManager.GetString("CLSyncEngineReleaseResourcesStopFileMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ReleaseResources: Stop IconOverlay..
        /// </summary>
        internal static string CLSyncEngineReleaseResourcesStoppingIconOverlay {
            get {
                return ResourceManager.GetString("CLSyncEngineReleaseResourcesStoppingIconOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ReleaseResources: Stop the Indexer..
        /// </summary>
        internal static string CLsyncEngineReleaseResourcesStopTheIndexer {
            get {
                return ResourceManager.GetString("CLsyncEngineReleaseResourcesStopTheIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: SyncReset: ERROR: {0}..
        /// </summary>
        internal static string CLSyncEngineResetError0 {
            get {
                return ResourceManager.GetString("CLSyncEngineResetError0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: OnNotificationReceived: Send a Perform PushNotification to monitor..
        /// </summary>
        internal static string CLSyncEngineSendAPerformPushNotificationToMonitor {
            get {
                return ResourceManager.GetString("CLSyncEngineSendAPerformPushNotificationToMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: Entry..
        /// </summary>
        internal static string CLSyncEngineStartEntry {
            get {
                return ResourceManager.GetString("CLSyncEngineStartEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: ERROR: {0}..
        /// </summary>
        internal static string CLSyncEngineStartError {
            get {
                return ResourceManager.GetString("CLSyncEngineStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: ERROR(2): {0}..
        /// </summary>
        internal static string CLSyncEngineStartError2 {
            get {
                return ResourceManager.GetString("CLSyncEngineStartError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: ERROR(4): Msg: {0}. Code: {1}..
        /// </summary>
        internal static string CLSyncEngineStartError4Msg0Code1 {
            get {
                return ResourceManager.GetString("CLSyncEngineStartError4Msg0Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: ERROR: Exception. Msg: {0}. Code: {1}..
        /// </summary>
        internal static string CLSyncEngineStartErrorExceptionMsg1Code1 {
            get {
                return ResourceManager.GetString("CLSyncEngineStartErrorExceptionMsg1Code1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: Hook up events..
        /// </summary>
        internal static string CLSyncEngineStartHookupEvents {
            get {
                return ResourceManager.GetString("CLSyncEngineStartHookupEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: Start the indexer..
        /// </summary>
        internal static string CLSyncEngineStartIndexer {
            get {
                return ResourceManager.GetString("CLSyncEngineStartIndexer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Starting....
        /// </summary>
        internal static string CLSyncEngineStarting {
            get {
                return ResourceManager.GetString("CLSyncEngineStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Start: Start the notifier..
        /// </summary>
        internal static string CLSyncEngineStartNotifier {
            get {
                return ResourceManager.GetString("CLSyncEngineStartNotifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: Stop: Entry..
        /// </summary>
        internal static string CLSyncEngineStopEntry {
            get {
                return ResourceManager.GetString("CLSyncEngineStopEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ReleaseResources: Stop the sync engine..
        /// </summary>
        internal static string CLSyncEngineStopTheSyncEngine {
            get {
                return ResourceManager.GetString("CLSyncEngineStopTheSyncEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: ReleaseResources: Sync engine stopped..
        /// </summary>
        internal static string CLSyncEngineSyncEngineStopped {
            get {
                return ResourceManager.GetString("CLSyncEngineSyncEngineStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: SyncReset: ERROR: From DeleteEverythingInDirectory.  Message: {0}..
        /// </summary>
        internal static string CLSyncEngineSyncResetDeleteEverythingInDirMessage0 {
            get {
                return ResourceManager.GetString("CLSyncEngineSyncResetDeleteEverythingInDirMessage0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: SyncReset: Entry..
        /// </summary>
        internal static string CLSyncEngineSyncResetEntry {
            get {
                return ResourceManager.GetString("CLSyncEngineSyncResetEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLSyncEngine: SyncReset: ERROR: Exception.  Msg: &lt;{0}&gt;..
        /// </summary>
        internal static string CLSyncEngineSyncResetERRORExceptionMsg0 {
            get {
                return ResourceManager.GetString("CLSyncEngineSyncResetERRORExceptionMsg0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientDescription must not contain commas.
        /// </summary>
        internal static string CLSyncSettingsClientDescriptionCannotContainCommas {
            get {
                return ResourceManager.GetString("CLSyncSettingsClientDescriptionCannotContainCommas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientDescription must have 32 or fewer characters.
        /// </summary>
        internal static string CLSyncSettingsClientDescriptionTooLong {
            get {
                return ResourceManager.GetString("CLSyncSettingsClientDescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncSettings must not be null.
        /// </summary>
        internal static string CLSyncSettingsMustNotBeNull {
            get {
                return ResourceManager.GetString("CLSyncSettingsMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncRoot must not be null.
        /// </summary>
        internal static string CLSyncSettingsSyncRootCannotBeNull {
            get {
                return ResourceManager.GetString("CLSyncSettingsSyncRootCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toCopy must not be null.
        /// </summary>
        internal static string CLSyncSettingstoCopyMustNotBeNull {
            get {
                return ResourceManager.GetString("CLSyncSettingstoCopyMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgramData\Microsoft\Windows.
        /// </summary>
        internal static string CommonStartMenuParentFolderNameVista {
            get {
                return ResourceManager.GetString("CommonStartMenuParentFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents and Settings\All Users.
        /// </summary>
        internal static string CommonStartMenuParentFolderNameXP {
            get {
                return ResourceManager.GetString("CommonStartMenuParentFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string DocumentsAndSettingsVista {
            get {
                return ResourceManager.GetString("DocumentsAndSettingsVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents and Settings.
        /// </summary>
        internal static string DocumentsAndSettingsXP {
            get {
                return ResourceManager.GetString("DocumentsAndSettingsXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string DocumentsFolderNameVista {
            get {
                return ResourceManager.GetString("DocumentsFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        internal static string DocumentsFolderNameXP {
            get {
                return ResourceManager.GetString("DocumentsFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  We&apos;re sorry, it seems that something went wrong while requesting status from the server..
        /// </summary>
        internal static string ErrorPostingSyncFromServer {
            get {
                return ResourceManager.GetString("ErrorPostingSyncFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  We&apos;re sorry, it seems that something went wrong while syncing files to the server..
        /// </summary>
        internal static string ErrorPostingSyncToServer {
            get {
                return ResourceManager.GetString("ErrorPostingSyncToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.  We&apos;re sorry, it seems that something when wrong while starting a server file upload or download. .
        /// </summary>
        internal static string ErrorPuttingUploadOrDownloadToServer {
            get {
                return ResourceManager.GetString("ErrorPuttingUploadOrDownloadToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while creating your account.  The error code is {0}..
        /// </summary>
        internal static string ExceptionCreatingUserRegistrationWithCode {
            get {
                return ResourceManager.GetString("ExceptionCreatingUserRegistrationWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 must be 128 bits (a byte array of length 16).
        /// </summary>
        internal static string ExceptionFileChangeSetMD5ByteLength {
            get {
                return ResourceManager.GetString("ExceptionFileChangeSetMD5ByteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendBackChange cannot be null.
        /// </summary>
        internal static string ExceptionFileChangeUpDownEventArgsNullSendBackChange {
            get {
                return ResourceManager.GetString("ExceptionFileChangeUpDownEventArgsNullSendBackChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rootPathObject must start with a upper-case drive letter.
        /// </summary>
        internal static string ExceptionHelpersCheckForBadPathDriveLetter {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckForBadPathDriveLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rootPathObject root drive letter represents an invalid DriveType: {0}.
        /// </summary>
        internal static string ExceptionHelpersCheckForBadPathDriveType {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckForBadPathDriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rootPathObject cannot have an empty directory name for any directory in the parent path hierarchy and cannot have a trailing slash.
        /// </summary>
        internal static string ExceptionHelpersCheckForBadPathEmptyDirectory {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckForBadPathEmptyDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rootPathObject must start at a drive letter and have a proceeding trailing slash.
        /// </summary>
        internal static string ExceptionHelpersCheckForBadPathProceedingSlash {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckForBadPathProceedingSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TraceCategory must not be null.
        /// </summary>
        internal static string ExceptionHelpersCheckLogFileExistanceTraceCategoryNull {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckLogFileExistanceTraceCategoryNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncRootFullPath is too long by {0} characters.
        /// </summary>
        internal static string ExceptionHelpersCheckSyncRootLengthTooLongPlural {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckSyncRootLengthTooLongPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syncRootFullPath is too long by {0} character.
        /// </summary>
        internal static string ExceptionHelpersCheckSyncRootLengthTooLongSingular {
            get {
                return ResourceManager.GetString("ExceptionHelpersCheckSyncRootLengthTooLongSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve property values on an invalid DictionaryTryGetValueResult.
        /// </summary>
        internal static string ExceptionHelpersDictionaryTryGetValueResultInvalid {
            get {
                return ResourceManager.GetString("ExceptionHelpersDictionaryTryGetValueResultInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hashString must be in a hexadecimal string format with no seperator characters and two characters per byte.
        /// </summary>
        internal static string ExceptionHelpersParseHexadecimalStringToByteArrayHashStringFormat {
            get {
                return ResourceManager.GetString("ExceptionHelpersParseHexadecimalStringToByteArrayHashStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed all retries with a numRetries of {0}.
        /// </summary>
        internal static string ExceptionHelpersRunActionWithRetriesFailedRetries {
            get {
                return ResourceManager.GetString("ExceptionHelpersRunActionWithRetriesFailedRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toRun cannot be null.
        /// </summary>
        internal static string ExceptionHelpersRunActionWithRetriesNullToRun {
            get {
                return ResourceManager.GetString("ExceptionHelpersRunActionWithRetriesNullToRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ListRemoveAllEnumerator has already been disposed.
        /// </summary>
        internal static string ExceptionListRemoveAllEnumeratorDisposed {
            get {
                return ResourceManager.GetString("ExceptionListRemoveAllEnumeratorDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset not supported.
        /// </summary>
        internal static string ExceptionListRemoveAllEnumeratorReset {
            get {
                return ResourceManager.GetString("ExceptionListRemoveAllEnumeratorReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while logging into your account.  The error code is {0}..
        /// </summary>
        internal static string ExceptionLoggingInWithCode {
            get {
                return ResourceManager.GetString("ExceptionLoggingInWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while removing this device from your account..
        /// </summary>
        internal static string ExceptionUnlinking {
            get {
                return ResourceManager.GetString("ExceptionUnlinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops. We&apos;re sorry, it seems like something went wrong while removing this device from your account.  The error code is {0}..
        /// </summary>
        internal static string ExceptionUnlinkingWithCode {
            get {
                return ResourceManager.GetString("ExceptionUnlinkingWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData\Local.
        /// </summary>
        internal static string LocalAppDataFolderNameVista {
            get {
                return ResourceManager.GetString("LocalAppDataFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Settings\Application Data.
        /// </summary>
        internal static string LocalAppDataFolderNameXP {
            get {
                return ResourceManager.GetString("LocalAppDataFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply a modification to a folder.
        /// </summary>
        internal static string MonitorAgentCannotApplyAModificationToAFolder {
            get {
                return ResourceManager.GetString("MonitorAgentCannotApplyAModificationToAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply a Sync To FileChange locally.
        /// </summary>
        internal static string MonitorAgentCannotApplySyncToFileChangeLocally {
            get {
                return ResourceManager.GetString("MonitorAgentCannotApplySyncToFileChangeLocally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download a file in MonitorAgent, it needs to be downloaded through Sync.
        /// </summary>
        internal static string MonitorAgentCannotDownloadAFileInMonitorAgentMustBeDownloadedThroughSync {
            get {
                return ResourceManager.GetString("MonitorAgentCannotDownloadAFileInMonitorAgentMustBeDownloadedThroughSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkDisposed cannot be null.
        /// </summary>
        internal static string MonitorAgentcheckDisposedCannotBeNull {
            get {
                return ResourceManager.GetString("MonitorAgentcheckDisposedCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on applying sync from directory move and an error checking if directory exists at new path.
        /// </summary>
        internal static string MonitorAgentErrorApplyingSyncfromDirectoryMoveandAnErrorCheckingIfDirectoryExistsAtNewPath {
            get {
                return ResourceManager.GetString("MonitorAgentErrorApplyingSyncfromDirectoryMoveandAnErrorCheckingIfDirectoryExists" +
                        "AtNewPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in GetUploadDownloadTransfersInProgress.
        /// </summary>
        internal static string MonitorAgentErrorGettingUploadTransferProgress {
            get {
                return ResourceManager.GetString("MonitorAgentErrorGettingUploadTransferProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error grabbing hierarchy from upDownsForDeleted.
        /// </summary>
        internal static string MonitorAgentErrorGrabbingHierarchyFromupDowsForDeleted {
            get {
                return ResourceManager.GetString("MonitorAgentErrorGrabbingHierarchyFromupDowsForDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error grabbing hierarchy from upDownsForRenamed.
        /// </summary>
        internal static string MonitorAgentErrorGrabbingHierarchyFromupDowsForRenamed {
            get {
                return ResourceManager.GetString("MonitorAgentErrorGrabbingHierarchyFromupDowsForRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in CreationModificationDependencyCheck.
        /// </summary>
        internal static string MonitorAgentErrorInCreationModifactionDependencyCheck {
            get {
                return ResourceManager.GetString("MonitorAgentErrorInCreationModifactionDependencyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in DeleteDependencyCheck.
        /// </summary>
        internal static string MonitorAgentErrorInDeleteDependencyCheck {
            get {
                return ResourceManager.GetString("MonitorAgentErrorInDeleteDependencyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in RenameDependencyCheck.
        /// </summary>
        internal static string MonitorAgentErrorInRenameDependencyCheck {
            get {
                return ResourceManager.GetString("MonitorAgentErrorInRenameDependencyCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating creation time for folder to event in database.
        /// </summary>
        internal static string MonitorAgentErrorUpdatingCreationTimeForFolderToEventDatabase {
            get {
                return ResourceManager.GetString("MonitorAgentErrorUpdatingCreationTimeForFolderToEventDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception on main ApplySyncFromFileChange switch and exception on onBeforeAllPathsUnlock.
        /// </summary>
        internal static string MonitorAgentExceptionOnMainApplySyncFromFileChangeSwitchandExceptionononBeforeAllPathsUnlock {
            get {
                return ResourceManager.GetString("MonitorAgentExceptionOnMainApplySyncFromFileChangeSwitchandExceptionononBeforeAll" +
                        "PathsUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileChange&apos;s NewPath does not fall within the root directory.
        /// </summary>
        internal static string MonitorAgentFileChangesNewPathDoesNotFallWithinTheRootDirectory {
            get {
                return ResourceManager.GetString("MonitorAgentFileChangesNewPathDoesNotFallWithinTheRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder not found at provided folder path.
        /// </summary>
        internal static string MonitorAgentFolderNotFoundAtProvidedPath {
            get {
                return ResourceManager.GetString("MonitorAgentFolderNotFoundAtProvidedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder path cannot be null or empty.
        /// </summary>
        internal static string MonitorAgentFolderPathCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("MonitorAgentFolderPathCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUploadDownloadTransfersInProgress return cannot have a null Key.
        /// </summary>
        internal static string MonitorAgentGetUploadTranfersInProgressReturnCannotHaveNullKey {
            get {
                return ResourceManager.GetString("MonitorAgentGetUploadTranfersInProgressReturnCannotHaveNullKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance not available until after Initialize is called.
        /// </summary>
        internal static string MonitorAgentInstanceNotAvailableAfterInitializeIsCalled {
            get {
                return ResourceManager.GetString("MonitorAgentInstanceNotAvailableAfterInitializeIsCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toAdd cannot be null.
        /// </summary>
        internal static string MonitorAgentToAddCannotBeNull {
            get {
                return ResourceManager.GetString("MonitorAgentToAddCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown FileChangeType for InnerFileChange:.
        /// </summary>
        internal static string MonitorAgentUnknownFileChangeTypeforInnerFileChange {
            get {
                return ResourceManager.GetString("MonitorAgentUnknownFileChangeTypeforInnerFileChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        internal static string MusicFolderNameVista {
            get {
                return ResourceManager.GetString("MusicFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Music.
        /// </summary>
        internal static string MusicFolderNameXP {
            get {
                return ResourceManager.GetString("MusicFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PossiblyUnmanagedCode.
        /// </summary>
        internal static string NoSpacesHelpersGetDefaultNameFromApplicationNameDefault {
            get {
                return ResourceManager.GetString("NoSpacesHelpersGetDefaultNameFromApplicationNameDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppDataFolderNameVista.
        /// </summary>
        internal static string NotTranslatedAppDataFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedAppDataFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace-????-??-??-.
        /// </summary>
        internal static string NotTranslatedCheckLogFileExistanceSearchStart {
            get {
                return ResourceManager.GetString("NotTranslatedCheckLogFileExistanceSearchStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *..
        /// </summary>
        internal static string NotTranslatedCheckLogFileExistanceStarDot {
            get {
                return ResourceManager.GetString("NotTranslatedCheckLogFileExistanceStarDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace-.
        /// </summary>
        internal static string NotTranslatedCheckLogFileExistanceTrace {
            get {
                return ResourceManager.GetString("NotTranslatedCheckLogFileExistanceTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd-.
        /// </summary>
        internal static string NotTranslatedCheckLogFileExistanceYearMonthDay {
            get {
                return ResourceManager.GetString("NotTranslatedCheckLogFileExistanceYearMonthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonStartMenuParentFolderNameVista.
        /// </summary>
        internal static string NotTranslatedCommonStartMenuParentFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedCommonStartMenuParentFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonStartMenuParentFolderNameXP.
        /// </summary>
        internal static string NotTranslatedCommonStartMenuParentFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedCommonStartMenuParentFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentsAndSettingsVista.
        /// </summary>
        internal static string NotTranslatedDocumentsAndSettingsVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedDocumentsAndSettingsVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentsAndSettingsXP.
        /// </summary>
        internal static string NotTranslatedDocumentsAndSettingsXPName {
            get {
                return ResourceManager.GetString("NotTranslatedDocumentsAndSettingsXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentsFolderNameVista.
        /// </summary>
        internal static string NotTranslatedDocumentsFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedDocumentsFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocumentsFolderNameXP.
        /// </summary>
        internal static string NotTranslatedDocumentsFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedDocumentsFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op_Explicit.
        /// </summary>
        internal static string NotTranslatedExplicitOperator {
            get {
                return ResourceManager.GetString("NotTranslatedExplicitOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-z]:\\$.
        /// </summary>
        internal static string NotTranslatedHelpersCheckForBadPathDriveLetterRegex {
            get {
                return ResourceManager.GetString("NotTranslatedHelpersCheckForBadPathDriveLetterRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:##.##} {1}.
        /// </summary>
        internal static string NotTranslatedHelpersFormatBytesString {
            get {
                return ResourceManager.GetString("NotTranslatedHelpersFormatBytesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertTo.
        /// </summary>
        internal static string NotTranslatedHelpersMethodInfoConvertTo {
            get {
                return ResourceManager.GetString("NotTranslatedHelpersMethodInfoConvertTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultForType.
        /// </summary>
        internal static string NotTranslatedHelpersMethodInfoDefaultForType {
            get {
                return ResourceManager.GetString("NotTranslatedHelpersMethodInfoDefaultForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op_Implicit.
        /// </summary>
        internal static string NotTranslatedImplicitOperator {
            get {
                return ResourceManager.GetString("NotTranslatedImplicitOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalAppDataFolderNameVista.
        /// </summary>
        internal static string NotTranslatedLocalAppDataFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedLocalAppDataFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalAppDataFolderNameXP.
        /// </summary>
        internal static string NotTranslatedLocalAppDataFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedLocalAppDataFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicFolderNameVista.
        /// </summary>
        internal static string NotTranslatedMusicFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedMusicFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MusicFolderNameXP.
        /// </summary>
        internal static string NotTranslatedMusicFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedMusicFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PicturesFolderNameVista.
        /// </summary>
        internal static string NotTranslatedPicturesFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedPicturesFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PicturesFolderNameXP.
        /// </summary>
        internal static string NotTranslatedPicturesFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedPicturesFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicUserNameVista.
        /// </summary>
        internal static string NotTranslatedPublicUserNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedPublicUserNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublicUserNameXP.
        /// </summary>
        internal static string NotTranslatedPublicUserNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedPublicUserNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoamingAppDataFolderNameVista.
        /// </summary>
        internal static string NotTranslatedRoamingAppDataFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedRoamingAppDataFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoamingAppDataFolderNameXP.
        /// </summary>
        internal static string NotTranslatedRoamingAppDataFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedRoamingAppDataFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartMenuFolderNameVista.
        /// </summary>
        internal static string NotTranslatedStartMenuFolderNameVistaName {
            get {
                return ResourceManager.GetString("NotTranslatedStartMenuFolderNameVistaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartMenuFolderNameXP.
        /// </summary>
        internal static string NotTranslatedStartMenuFolderNameXPName {
            get {
                return ResourceManager.GetString("NotTranslatedStartMenuFolderNameXPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemDrive.
        /// </summary>
        internal static string NotTranslatedSystemDrive {
            get {
                return ResourceManager.GetString("NotTranslatedSystemDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.0.0.0.
        /// </summary>
        internal static string NotTranslatedZeroedVersion {
            get {
                return ResourceManager.GetString("NotTranslatedZeroedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bits.
        /// </summary>
        internal static string OsBits {
            get {
                return ResourceManager.GetString("OsBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string PicturesFolderNameVista {
            get {
                return ResourceManager.GetString("PicturesFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Pictures.
        /// </summary>
        internal static string PicturesFolderNameXP {
            get {
                return ResourceManager.GetString("PicturesFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        internal static string PublicUserNameVista {
            get {
                return ResourceManager.GetString("PublicUserNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users.
        /// </summary>
        internal static string PublicUserNameXP {
            get {
                return ResourceManager.GetString("PublicUserNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData\Roaming.
        /// </summary>
        internal static string RoamingAppDataFolderNameVista {
            get {
                return ResourceManager.GetString("RoamingAppDataFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Data.
        /// </summary>
        internal static string RoamingAppDataFolderNameXP {
            get {
                return ResourceManager.GetString("RoamingAppDataFolderNameXP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData\Roaming\Microsoft\Windows\Start Menu.
        /// </summary>
        internal static string StartMenuFolderNameVista {
            get {
                return ResourceManager.GetString("StartMenuFolderNameVista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Menu.
        /// </summary>
        internal static string StartMenuFolderNameXP {
            get {
                return ResourceManager.GetString("StartMenuFolderNameXP", resourceCulture);
            }
        }
    }
}
