//
// CLSyncBox.cs
// Cloud Windows
//
// Created By DavidBruck.
// Copyright (c) Cloud.com. All rights reserved.

using CloudApiPublic.Interfaces;
using CloudApiPublic.Model;
using CloudApiPublic.Static;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CloudApiPublic
{
    /// <summary>
    /// Represents a SyncBox in Cloud where everything is stored
    /// </summary>
    public sealed class CLSyncBox
    {
        /// <summary>
        /// Contains authentication information required for all communication and services
        /// </summary>
        public CLCredential Credentials
        {
            get
            {
                return _credentials;
            }
        }
        private readonly CLCredential _credentials;

        /// <summary>
        /// The unique ID of this SyncBox assigned by Cloud
        /// </summary>
        public long SyncBoxId
        {
            get
            {
                return _syncBoxId;
            }
        }
        private readonly long _syncBoxId;

        /// <summary>
        /// Settings copied upon creation of this SyncBox
        /// </summary>
        public ICLSyncSettingsAdvanced CopiedSettings
        {
            get
            {
                return _copiedSettings;
            }
        }
        private readonly ICLSyncSettingsAdvanced _copiedSettings;

        /// <summary>
        /// Creates an object which represents a SyncBox in Cloud
        /// </summary>
        /// <param name="Credentials">Credentials to authenticate communication</param>
        /// <param name="SyncBoxId">Unique ID of the SyncBox generated by Cloud</param>
        /// <param name="syncBox">(output) Created local object representation of SyncBox</param>
        /// <param name="status">(output) Status of creation, should be checked for success</param>
        /// <param name="Settings">(optional) Settings to allow use of the SyncBox in CLSyncEngine for active syncing and/or to allow tracing or other options</param>
        /// <returns>Returns any error which occurred during creation, if any</returns>
        public static CLError CreateAndInitialize(
            CLCredential Credentials,
            long SyncBoxId,
            out CLSyncBox syncBox,
            out CLSyncBoxCreationStatus status,
            ICLSyncSettings Settings = null)
        {
            status = CLSyncBoxCreationStatus.ErrorUnknown;

            try
            {
                syncBox = new CLSyncBox(
                    Credentials,
                    SyncBoxId,
                    Settings,
                    ref status);
            }
            catch (Exception ex)
            {
                syncBox = Helpers.DefaultForType<CLSyncBox>();
                return ex;
            }

            status = CLSyncBoxCreationStatus.Success;
            return null;
        }
        private CLSyncBox(CLCredential Credentials,
            long SyncBoxId,
            ICLSyncSettings Settings,
            ref CLSyncBoxCreationStatus status)
        {
            // check input parameters

            if (Credentials == null)
            {
                status = CLSyncBoxCreationStatus.ErrorNullCredentials;
                throw new NullReferenceException("Credentials cannot be null");
            }

            this._credentials = Credentials;
            this._syncBoxId = SyncBoxId;
            if (Settings == null)
            {
                this._copiedSettings = AdvancedSyncSettings.CreateDefaultSettings();
            }
            else
            {
                this._copiedSettings = Settings.CopySettings();
            }
        }
    }
    /// <summary>
    /// Status of creation of <see cref="CLSyncBox"/>
    /// </summary>
    public enum CLSyncBoxCreationStatus : byte
    {
        Success,
        ErrorNullCredentials,
        ErrorUnknown
    }
}